schema_version: 1

context:
  name: ms_peak_picker
  version: 0.1.46

package:
  name: ${{ name|lower }}
  version: ${{ version }}

source:
  url: https://pypi.org/packages/source/${{ name[0] }}/${{ name }}/ms_peak_picker-${{ version }}.tar.gz
  sha256: 3fee82ede3ea53a3b266d514fe26da68b48acbdfdf01f25870b51c5754f35670

build:
  number: 0
  script: ${{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation

requirements:
  build:
    - if: build_platform != target_platform
      then:
        - python
        - cross-python_${{ target_platform }}
        - numpy

    - ${{ compiler('c') }}
    - ${{ stdlib('c') }}
  host:
    - python
    - setuptools
    - pip
    - wheel
    - cython
    - numpy >=2.0.0
  run:
    - python
    - numpy >=2.0.0
    - scipy
    - six

tests:
  - python:
      imports:
        - ms_peak_picker
  - requirements:
      run:
        - pytest
    files:
      source:
        - tests/
    script:
      # NOTE: we must ignore the other tests because of ImportError due
      # to a __init__.py file in the tests directory
      - pytest -vvv tests/test_library.py

about:
  summary: A library to pick peaks from mass spectral data
  license: Apache-2.0
  license_file: LICENSE
  homepage: https://github.com/mobiusklein/ms_peak_picker

extra:
  recipe-maintainers:
    - hadim
